// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"time"

	"github.com/google/uuid"
)

type TrackActivity struct {
	ID        int32
	UserID    uuid.UUID
	TrackID   string
	IsLiked   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
